export const DOCUMENTS_LOADING = 'DOCUMENTS_LOADING';
export const DOCUMENTS_LOADED = 'DOCUMENTS_LOADED';
export const DOCUMENTS_ERROR = 'DOCUMENTS_ERROR';

export const CLEAR_DOCUMENT = 'CLEAR_DOCUMENT';
export const TOGGLE_DOCUMENT_FORM = 'TOGGLE_DOCUMENT_FORM';
export const DOCUMENT_LOADING = 'DOCUMENT_LOADING';
export const DOCUMENT_LOADED = 'DOCUMENT_LOADED';
export const QUEUE_DOCUMENT_TO_DELETE = 'QUEUE_DOCUMENT_TO_DELETE';
export const DOCUMENT_DELETED = 'DOCUMENT_DELETED';
export const DOCUMENT_ERROR = 'DOCUMENT_ERROR';

export const RESOURCES_LOADING = 'RESOURCES_LOADING';
export const RESOURCES_LOADED = 'RESOURCES_LOADED';
export const RESOURCES_ERROR = 'RESOURCES_ERROR';

export const CLEAR_RESOURCE = 'CLEAR_RESOURCE';
export const TOGGLE_RESOURCE_FORM = 'TOGGLE_RESOURCE_FORM';
export const RESOURCE_LOADING = 'RESOURCE_LOADING';
export const RESOURCE_LOADED = 'RESOURCE_LOADED';
export const QUEUE_RESOURCE_TO_DELETE = 'QUEUE_RESOURCE_TO_DELETE';
export const RESOURCE_DELETED = 'RESOURCE_DELETED';
export const RESOURCE_ERROR = 'RESOURCE_ERROR';
